name: trivia-quiz 
base: core24
adopt-info: trivia-quiz
grade: stable 
confinement: strict 
compression: lzo
platforms:
  amd64:
  arm64:

parts:
  trivia-quiz:
    plugin: meson
    source: https://github.com/Nokse22/trivia-quiz.git
    source-tag: 'v1.0.1'
    source-depth: 1
    parse-info: [ usr/share/metainfo/io.github.nokse22.trivia-quiz.metainfo.xml ]
    build-snaps:
      - blueprint-compiler/latest/edge
    meson-parameters:
      - --prefix=/snap/trivia-quiz/current/usr
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/trivia-quiz/current/usr/bin/trivia-quiz
      chmod +x $CRAFT_PART_INSTALL/snap/trivia-quiz/current/usr/bin/trivia-quiz
    organize:
      snap/trivia-quiz/current: .

slots:
  trivia-quiz:
    interface: dbus
    bus: session
    name: io.github.nokse22.trivia-quiz

apps:
  trivia-quiz:
    command: usr/bin/trivia-quiz
    extensions: [ gnome ]
    common-id: io.github.nokse22.trivia-quiz
    desktop: usr/share/applications/io.github.nokse22.trivia-quiz.desktop
    plugs:
      - network
